version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    labels:
      - "cargo"
      - "dependencies"
    commit-message:
      prefix: "ğŸ“¦"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - "actions"
      - "dependencies"
    commit-message:
      prefix: "ğŸ› ï¸"
